profanity_ignore_groups = ["загон", "владыка мира нексуса"]
non_user_channels = ["заходившие"]
command_channel = ["загон"]
music_channel = ["KozaDJ"]
log_channel = "логи-бота"
PREFIX = "!"
games = ["Heroes of the Storm", "Skyrim: Goat Edition", "Warcraft 3: Refunded", "сыщика", "грязные игры"]
watching = ["на тебя!", "стрим HappyDerg", "Netflix", "акции Activision Blizzard", "темы на форуме"]
blizzcon = "трансляцию Blizzcon 2021"
listening = ["Авторадио", "Хард Рок", "музыку в Spotify", "сплетни бабки"]
