profanity_ignore_groups = ["загон", "владыка мира нексуса"]
non_user_channels = ["заходившие"]
command_channel = ["загон"]
music_channel = ["KozaDJ"]
log_channel = "логи-бота"
PREFIX = "!"
game = "Heroes of the Storm"
watching = "на тебя!"
blizzcon = "трансляцию Blizzcon 2021"
happy_derg = "стрим HappyDerg"
listening = "Авторадио"
